@extends('layouts.frontend')
@section('frontend-content')
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">
<style>.credit-list{background:#f5f7fb;padding:32px 0;min-height:60vh}.credit-list .card{border:0;border-radius:15px;box-shadow:0 10px 25px rgba(18,34,56,.07)}.credit-list .card-header{background:#fff;border-bottom:1px solid #e7edf5;padding:20px;font:800 20px 'Barlow Condensed',sans-serif}.credit-list .table thead{background:#172b49;color:#fff}.credit-list .table th{font-size:11px;text-transform:uppercase;letter-spacing:.05em;border-top:0;padding:14px!important}.credit-list .table td{vertical-align:middle;padding:13px!important;border-color:#edf1f5!important}.credit-status{padding:6px 10px;border-radius:20px;font-size:11px;font-weight:800}.credit-status.Pending{background:#fff4df;color:#ad6800}.credit-status.Active{background:#e9faf4;color:#087f5b}.credit-status.Inactive,.credit-status.Suspended{background:#fff0f0;color:#c92a2a}.icon-action{width:34px;height:34px;display:inline-grid;place-items:center;border-radius:8px;border:1px solid #dbe4ef;color:#2454b9;text-decoration:none}.icon-action:hover{background:#eef4ff}.dataTables_wrapper .dataTables_filter input,.dataTables_wrapper .dataTables_length select{border:1px solid #dbe4ef;border-radius:8px;padding:6px 10px}</style>
<section class="credit-list"><div class="container"><div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><div><h2 class="mb-1" style="font-family:'Barlow Condensed';font-weight:800">Wallet & credit</h2><small class="text-muted">Your credit applications and approved limits</small></div><a class="btn btn-primary" style="background:#3566e8;border:0;border-radius:7px;font-weight:700" href="{{ route('frontend.wallet-requests.create') }}"><i class="fa-solid fa-plus me-1"></i> Apply for credit</a></div>@if(session('message'))<div class="alert alert-info">{{ session('message') }}</div>@endif<div class="card"><div class="card-header"><i class="fa-solid fa-wallet me-2"></i>Credit line history</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0 datatable-wallet w-100"><thead><tr><th>Application</th><th>Requested / approved amount</th><th>Status</th><th>Applied on</th><th>Action</th></tr></thead><tbody>@foreach($walletRequests as $walletRequest)<tr><td><strong>#{{ $walletRequest->id }}</strong></td><td>Rs {{ number_format($walletRequest->welcome_amount ?? 0,2) }}</td><td><span class="credit-status {{ $walletRequest->status }}">{{ App\Models\WalletRequest::STATUS_SELECT[$walletRequest->status] ?? $walletRequest->status }}</span></td><td>{{ optional($walletRequest->created_at)->format('d M Y') }}</td><td>@if($walletRequest->status === 'Active')<a class="icon-action" href="{{ route('frontend.wallet.statement') }}" title="View statement"><i class="fa-solid fa-file-lines"></i></a>@else<span class="text-muted">N/A</span>@endif</td></tr>@endforeach</tbody></table></div></div></div></div></section>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script>
<script>$(function(){ $('.datatable-wallet').DataTable({ pageLength:5, lengthMenu:[[5,10,25,50],[5,10,25,50]] }); });</script>
@endsection
