@extends('layouts.frontend')
@section('frontend-content')
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">
<style>.statement{background:#f5f7fb;padding:32px 0;min-height:60vh}.statement .head{background:linear-gradient(115deg,#132640,#3566e8);color:#fff;border-radius:15px;padding:24px}.statement .head h1{font:800 27px 'Barlow Condensed';margin:0}.statement .metric{background:#fff;border-radius:11px;padding:16px;color:#172b49;border:1px solid #e7edf5}.statement .metric small{display:block;color:#718096;text-transform:uppercase;font-size:10px;font-weight:800}.statement .metric b{font-size:20px}.statement .card{border:0;border-radius:14px;box-shadow:0 10px 24px rgba(18,34,56,.06)}.statement .table thead{background:#172b49;color:#fff}.statement th{font-size:11px;text-transform:uppercase}.statement td,.statement th{vertical-align:middle!important;padding:14px!important;border-color:#edf1f5!important}.pay-btn{width:34px;height:34px;display:inline-grid;place-items:center;border-radius:8px;background:#3566e8;color:#fff;text-decoration:none}.pay-btn:hover{color:#fff;background:#244f98}.dataTables_wrapper .dataTables_filter input,.dataTables_wrapper .dataTables_length select{border:1px solid #dbe4ef;border-radius:8px;padding:6px 10px}</style>
<section class="statement"><div class="container"><div class="head mb-3"><h1>Credit line statement</h1><p class="mb-0 text-white-50">All invoice dues for the currently logged-in account.</p></div><div class="row g-3 mb-3"><div class="col-md-4"><div class="metric"><small>Available credit</small><b>Rs {{ number_format($wallet->welcome_amount,2) }}</b></div></div><div class="col-md-4"><div class="metric"><small>Outstanding due</small><b>Rs {{ number_format($wallet->due,2) }}</b></div></div><div class="col-md-4"><div class="metric"><small>Credit status</small><b>{{ $wallet->status }}</b></div></div></div><div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0 datatable-statement w-100"><thead><tr><th>Invoice</th><th>Credit used</th><th>Repaid</th><th>Remaining</th><th>Action</th></tr></thead><tbody>@foreach($orders as $order)<tr><td><b>{{ $order->order_number }}</b><small class="d-block text-muted">{{ optional($order->created_at)->format('d M Y') }}</small></td><td>Rs {{ number_format($order->total_amount,2) }}</td><td>Rs {{ number_format($order->repaid,2) }}</td><td><b>Rs {{ number_format($order->outstanding,2) }}</b></td><td>@if($order->outstanding > 0)<a href="{{ route('wallet.payout.form') }}?order_id={{ $order->id }}" class="pay-btn" title="Pay"><i class="fa-solid fa-indian-rupee-sign"></i></a>@else<span class="text-success"><i class="fa-solid fa-circle-check me-1"></i>Paid</span>@endif</td></tr>@endforeach</tbody></table></div></div></div></div></section>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script>
<script>$(function(){ $('.datatable-statement').DataTable({ pageLength:5, lengthMenu:[[5,10,25,50],[5,10,25,50]], order:[[0,'desc']] }); });</script>
@endsection
