@extends('custom.master')

@section('content')
@php
    $lines = collect($cartItems);
    $subtotal = $lines->sum(function ($item) { $price = Auth::guard('customer')->check() ? ($item['rate_2'] ?? $item['final_price'] ?? $item['price']) : ($item['final_price'] ?? $item['price_1'] ?? $item['price']); return (float) $price * (int) $item['quantity']; });
    $tax = $lines->sum(function ($item) { $price = Auth::guard('customer')->check() ? ($item['rate_2'] ?? $item['final_price'] ?? $item['price']) : ($item['final_price'] ?? $item['price_1'] ?? $item['price']); return $price * $item['quantity'] * ($item['gst'] ?? 0) / 100; });
    $total = $subtotal + $tax + ($orderSummary['deliveryFee'] ?? 0);
    $address = $user->address ?? null;
    $available = (float) ($wallet->welcome_amount ?? 0); $due = (float) ($wallet->due ?? 0);
@endphp
<style>
.checkout{background:#f6faff;border-radius:24px;padding:28px}.checkout-card{background:#fff;border:1px solid #e1eaf3;border-radius:18px;box-shadow:0 12px 30px #23456612}.order-line{padding:12px 0;border-bottom:1px solid #eef2f6}.order-line:last-child{border:0}.order-image{height:50px;width:50px;object-fit:contain;background:#f3f7fa;border-radius:10px}.summary{background:#172b4d;color:#fff;border-radius:16px}.summary .muted{color:#c5d4e7}.credit{background:#edf6ff;border:1px solid #cde3fb;border-radius:14px}.offer-option{border:1px solid #dfe8f1;border-radius:12px;padding:12px;cursor:pointer}.offer-option.active{border-color:#1767ae;background:#f0f7ff}
</style>
<section class="py-5"><div class="container"><div class="checkout"><div class="d-flex justify-content-between align-items-center mb-4"><div><small class="text-primary fw-bold text-uppercase">Secure checkout</small><h2 class="mb-0">Delivery & payment</h2></div><a href="{{ route('custom.cart') }}" class="btn btn-outline-primary">Back to cart</a></div>
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
@if($lines->isEmpty())<div class="alert alert-info">Your cart is empty. <a href="{{ route('custom.product') }}">Browse products</a></div>@else
<div class="row g-4"><div class="col-lg-7"><div class="checkout-card p-4 mb-4"><div class="d-flex justify-content-between"><h5><i class="fa-solid fa-location-dot text-primary me-2"></i>Delivery address</h5><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#addressModal">Edit</button></div><div class="mt-3 p-3 bg-light rounded"><strong>{{ $user->name }}</strong><div class="text-muted">{{ $address ? collect([$address->full_address,$address->district,$address->state,$address->country,$address->pin_code])->filter()->join(', ') : 'Add an address before placing your order.' }}</div><small>{{ $user->phone }} · {{ $user->email }}</small></div></div>
<div class="checkout-card p-4"><h5><i class="fa-solid fa-credit-card text-primary me-2"></i>Payment method</h5>
@if(Auth::guard('web')->check())<div class="credit p-3 my-3"><div class="d-flex justify-content-between"><strong>Pay later — Credit Line</strong><i class="fa-solid fa-wallet text-primary fs-4"></i></div><div class="row text-center mt-3"><div class="col"><small class="d-block text-muted">Available</small><strong>₹{{ number_format($available,2) }}</strong></div><div class="col"><small class="d-block text-muted">Used now</small><strong>₹{{ number_format($total,2) }}</strong></div><div class="col"><small class="d-block text-muted">Left</small><strong>₹{{ number_format(max(0,$available-$total),2) }}</strong></div></div></div>@endif
<form method="POST" action="{{ route('frontend.order.store') }}">@csrf @foreach($lines as $item)<input type="hidden" name="product[]" value="{{ $item['id'] }}"><input type="hidden" name="product_quantity[]" value="{{ $item['quantity'] }}">@endforeach<input type="hidden" name="products[]" value="{{ json_encode($cartItems) }}"><input type="hidden" name="email" value="{{ $user->email }}"><input type="hidden" name="name" value="{{ $user->name }}"><input type="hidden" name="phone" value="{{ $user->phone }}"><input type="hidden" name="country" value="{{ $address->country ?? '' }}"><input type="hidden" name="state" value="{{ $address->state ?? '' }}"><input type="hidden" name="district" value="{{ $address->district ?? '' }}"><input type="hidden" name="full_address" value="{{ $address->full_address ?? '' }}"><input type="hidden" name="total_amount" value="{{ $total }}"><input type="hidden" name="payment_method" value="Credit Line"><button class="btn btn-primary w-100" {{ !Auth::guard('web')->check() || !$wallet || $wallet->status !== 'Active' || $available < $total || !$address ? 'disabled' : '' }}>Pay later with Credit Line</button></form>
<button id="online-payment" type="button" class="btn btn-outline-primary w-100 mt-3">Pay securely with Razorpay</button></div></div>
<div class="col-lg-5"><div class="checkout-card p-4 mb-4"><h5>Your order <small class="text-muted">({{ $lines->count() }} items)</small></h5>@foreach($lines as $item)@php($price = Auth::guard('customer')->check() ? ($item['rate_2'] ?? $item['final_price'] ?? $item['price']) : ($item['final_price'] ?? $item['price_1'] ?? $item['price']))<div class="order-line d-flex gap-3"><img class="order-image" src="{{ $item['photo'] ?? asset('default.png') }}"><div class="flex-grow-1"><strong>{{ $item['name'] }}</strong>@include('custom.partials.selection', ['selection' => $item])<small class="d-block text-muted">Item code: {{ $item['item_code'] ?? '—' }} · Qty {{ $item['quantity'] }}</small></div><strong>₹{{ number_format($price*$item['quantity'],2) }}</strong></div>@endforeach</div><div class="summary p-4"><div class="d-flex justify-content-between muted"><span>Subtotal</span><span>₹{{ number_format($subtotal,2) }}</span></div><div class="d-flex justify-content-between muted mt-2"><span>GST</span><span>₹{{ number_format($tax,2) }}</span></div><div class="d-flex justify-content-between muted mt-2"><span>Delivery</span><span>{{ ($orderSummary['deliveryFee'] ?? 0) ? '₹'.number_format($orderSummary['deliveryFee'],2) : 'Free' }}</span></div><div id="discount-line" class="d-none text-success d-flex justify-content-between mt-2"><span>Online offer</span><span id="discount-amount"></span></div><hr><div class="d-flex justify-content-between fs-5 fw-bold"><span>Payable</span><span id="payable">₹{{ number_format($total,2) }}</span></div></div></div></div>@endif</div></div></section>
<div class="modal fade" id="addressModal"><div class="modal-dialog"><form action="{{ route('custom.delivery.store') }}" method="POST" class="modal-content">@csrf<div class="modal-header"><h5>Delivery address</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-12"><input class="form-control" name="full_address" required placeholder="Full address" value="{{ $address->full_address ?? '' }}"></div><div class="col-md-6"><input class="form-control" name="district" required placeholder="District" value="{{ $address->district ?? '' }}"></div><div class="col-md-6"><input class="form-control" name="state" required placeholder="State" value="{{ $address->state ?? '' }}"></div><div class="col-md-6"><input class="form-control" name="country" required placeholder="Country" value="{{ $address->country ?? 'India' }}"></div><div class="col-md-6"><input class="form-control" name="pin_code" placeholder="PIN" value="{{ $address->pin_code ?? '' }}"></div></div><div class="modal-footer"><button class="btn btn-primary">Save address</button></div></form></div></div>
<div class="modal fade" id="offerModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Online payment offer</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted small">Offers apply once per order and only to Razorpay payments.</p>@forelse($offers as $offer)<label class="offer-option d-block mb-2" data-id="{{ $offer->id }}" data-percent="{{ $offer->discount_percent }}"><input type="radio" name="offer" class="form-check-input me-2"><strong>{{ $offer->title }}</strong> <span class="badge text-bg-success">{{ $offer->discount_percent }}% off</span><small class="d-block text-muted ms-4">Minimum order ₹{{ number_format($offer->minimum_order_amount,2) }}</small></label>@empty<div class="alert alert-light border">No offer available for this order.</div>@endforelse</div><div class="modal-footer"><button id="without-offer" class="btn btn-outline-secondary">Continue without offer</button><button id="apply-offer" class="btn btn-primary">Apply & pay</button></div></div></div></div>
<form id="razorpay-form" class="d-none" action="{{ route('frontend.customer.payment.process') }}" method="POST">@csrf<input name="products" value="{{ json_encode($cartItems) }}"><input name="full_address" value="{{ $address ? collect([$address->full_address,$address->district,$address->state,$address->country,$address->pin_code])->filter()->join(', ') : '' }}"><input name="total_amount" id="online-total" value="{{ $total }}"><input name="offer_id" id="offer-id"><input name="razorpay_payment_id" id="payment-id"></form>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script><script>document.addEventListener('DOMContentLoaded',function(){const base={{ $total }},modal=new bootstrap.Modal(document.getElementById('offerModal'));let selected=null;document.getElementById('online-payment').onclick=()=>modal.show();document.querySelectorAll('.offer-option').forEach(x=>x.onclick=()=>{document.querySelectorAll('.offer-option').forEach(y=>y.classList.remove('active'));x.classList.add('active');selected={id:x.dataset.id,pct:+x.dataset.percent}});function pay(){let saving=selected?Math.round(base*selected.pct)/100:0,total=Math.max(0,base-saving);document.getElementById('online-total').value=total;document.getElementById('offer-id').value=selected?.id||'';document.getElementById('payable').textContent='₹'+total.toFixed(2);document.getElementById('discount-line').classList.toggle('d-none',!selected);document.getElementById('discount-amount').textContent='− ₹'+saving.toFixed(2);modal.hide();new Razorpay({key:"{{ config('services.razorpay.key') }}",amount:Math.round(total*100),currency:'INR',name:"{{ config('app.name') }}",handler:r=>{document.getElementById('payment-id').value=r.razorpay_payment_id;document.getElementById('razorpay-form').submit()},theme:{color:'#1767ae'}}).open()}document.getElementById('apply-offer').onclick=pay;document.getElementById('without-offer').onclick=()=>{selected=null;pay()}});</script>
@endsection
