@extends('custom.master')

@section('content')
@php $shipping = json_decode($order->shipping_address, true) ?: []; @endphp
<style>.dashboard{background:#f5f7fb}.panel{background:#fff;border:1px solid #e4ebf3;border-radius:14px;box-shadow:0 12px 28px rgba(18,34,56,.07);padding:20px}.panel h1{font:800 30px 'Barlow Condensed',sans-serif;color:#13243d}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.meta div{background:#f8fafc;border:1px solid #edf1f5;border-radius:10px;padding:12px}.meta small{display:block;color:#718096;text-transform:uppercase;font-weight:800;font-size:.68rem}.meta b{color:#13243d}.table thead{background:#172b49;color:#fff}.table th{font-size:11px;text-transform:uppercase}.actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:768px){.meta{grid-template-columns:1fr}}</style>
<section class="dashboard py-5"><div class="container"><div class="row">@include('custom.sidebar')<div class="col-lg-9"><div class="panel">
  <div class="d-flex justify-content-between gap-3 flex-wrap mb-3"><div><h1>Order {{ $order->order_number }}</h1><p class="text-muted mb-0">Order details and invoice actions.</p></div><div class="actions"><a href="{{ route('frontend.orders.index') }}" class="btn btn-outline-secondary"><i class="fa-solid fa-arrow-left me-1"></i>Back</a>@if(strtolower($order->order_status ?? '') === 'pending')<a href="{{ route('frontend.orders.edit', $order) }}" class="btn btn-warning"><i class="fa-regular fa-pen-to-square me-1"></i>Edit delivery</a>@endif<a href="{{ route('invoice.download', $order->order_number) }}" class="btn btn-danger"><i class="fa-regular fa-file-pdf me-1"></i>PDF</a></div></div>
  <div class="meta mb-4"><div><small>Amount</small><b>Rs {{ number_format($order->total_amount,2) }}</b></div><div><small>Status</small><b>{{ ucfirst($order->order_status ?? 'Pending') }}</b></div><div><small>Payment</small><b>{{ $order->payment_method ?? 'N/A' }}</b></div></div>
  <h5>Delivery Details</h5><p class="mb-4">{{ $shipping['contact_name'] ?? $order->select_user->name ?? $order->select_customer->name ?? 'N/A' }}<br>{{ $shipping['contact_phone'] ?? 'Phone not added' }} {{ !empty($shipping['contact_email']) ? ' · '.$shipping['contact_email'] : '' }}<br>{{ implode(', ', array_filter([$shipping['full_address'] ?? null, $shipping['district'] ?? null, $shipping['state'] ?? null, $shipping['country'] ?? null])) ?: 'No address found' }}</p>
  <h5>Items</h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>Qty</th><th>Price</th></tr></thead><tbody>@foreach($order->select_products as $product)<tr><td>{{ $product->name }}</td><td>{{ $product->pivot->quantity ?? 1 }}</td><td>Rs {{ number_format((float)($product->price_1 ?? $product->price ?? 0),2) }}</td></tr>@endforeach</tbody></table></div>
</div></div></div></div></section>
@endsection
